// Centralised German UI strings. Single source so a later i18n pass is cheap.
export const t = {
  app: {
    title: "Dashboard",
  },
  edit: {
    enter: "Bearbeiten",
    exit: "Fertig",
    reset: "Layout zurücksetzen",
    fold: "Bildschirmrand — alles darunter ist per Scrollen erreichbar",
    maximize: "Vollbild",
    closeMaximize: "Vollbild schließen",
  },
  warnings: {
    generic: "Wetterwarnung",
    until: (when: string) => `bis ${when}`,
    more: (n: number) => `+${n} weitere`,
  },
  mobile: {
    title: "Einkaufsliste",
    openDashboard: "Zum Dashboard",
  },
  widgets: {
    clock: {
      title: "Uhrzeit",
    },
    shopping: {
      title: "Einkaufsliste",
      productPlaceholder: "Was brauchen wir?",
      amountPlaceholder: "Menge",
      add: "+",
      empty: "Liste ist leer.",
      loading: "Lade…",
      error: "Liste konnte nicht geladen werden.",
      deleteLabel: "Löschen",
      exportLabel: "QR-Code anzeigen",
      exportTitle: "Liste auf's Handy",
      exportHint: "Mit der Handy-Kamera scannen — öffnet die Liste zum Mitnehmen und Abhaken.",
      close: "Schließen",
      copy: "Text kopieren",
      copied: "Kopiert",
      clearBought: "Erledigte aufräumen",
      clearAll: "Alle löschen",
      confirmClearAll: "Wirklich alle Einträge löschen?",
      boughtSection: "Erledigt",
    },
    calendar: {
      title: "Kalender",
      empty: "Keine kommenden Termine.",
      loading: "Lade Termine…",
      error: "Termine konnten nicht geladen werden.",
      addNew: "Neuer Termin",
      cancel: "Abbrechen",
      save: "Speichern",
      titleField: "Titel",
      dateField: "Datum",
      timeField: "Uhrzeit (optional)",
      allDay: "Ganztägig",
      deleteLabel: "Löschen",
      today: "Heute",
      tomorrow: "Morgen",
      freeDay: "frei",
      blocksHouse: "Belegt das Haus",
      areaField: "Bereich (z. B. Küche, Bad)",
      assignTo: "Wer?",
      icsImport: "ICS importieren",
      icsPlaceholder: "ICS-Inhalt hier einfügen…",
      icsImportButton: "Importieren",
      icsImported: (n: number) => (n === 1 ? "1 Termin importiert" : `${n} Termine importiert`),
      groupLabel: (d: Date) =>
        new Intl.DateTimeFormat("de-DE", {
          weekday: "long",
          day: "numeric",
          month: "long",
          timeZone: "Europe/Berlin",
        }).format(d),
    },
    parcels: {
      title: "Sendungen",
      empty: "Keine offenen Sendungen.",
      loading: "Lade…",
      error: "Sendungen konnten nicht geladen werden.",
      add: "+",
      cancel: "Abbrechen",
      save: "Speichern",
      trackingPlaceholder: "Sendungsnummer",
      labelPlaceholder: "Bezeichnung (optional)",
      carrierField: "Versanddienst",
      refreshLabel: "Aktualisieren",
      deleteLabel: "Löschen",
      openLabel: "Bei Versanddienst öffnen",
      status: {
        unknown: "Status unbekannt",
        in_transit: "unterwegs",
        out_for_delivery: "in Zustellung",
        available_for_pickup: "abholbereit",
        delivered: "zugestellt",
        exception: "Problem",
      },
      eta: (hhmm: string) => `Voraussichtlich ${hhmm}`,
      lastChecked: (mins: number) =>
        mins < 1 ? "gerade geprüft" : mins < 60 ? `vor ${mins} min geprüft` : `vor ${Math.floor(mins / 60)} h geprüft`,
      trackingHint:
        "Auto-Update inaktiv. Setze DASHBOARD_17TRACK_API_KEY (alle Versanddienste) für Live-Status.",
    },
    todos: {
      title: "Aufgaben",
      empty: "Keine offenen Aufgaben.",
      loading: "Lade…",
      error: "Aufgaben konnten nicht geladen werden.",
      add: "+",
      placeholder: "Was ist zu tun?",
      due: "Fällig",
      noDue: "kein Datum",
      overdue: "überfällig",
      today: "heute",
      tomorrow: "morgen",
      inDays: (n: number) => `in ${n} Tagen`,
      cancel: "Abbrechen",
      save: "Speichern",
      doneSection: "Erledigt",
      deleteLabel: "Löschen",
      clearDone: "Erledigte aufräumen",
      assignTo: "Wer?",
    },
    weather: {
      title: "Wetter Moosburg",
      loading: "Lade Wetter…",
      error: "Wetter nicht verfügbar.",
      stale: "Daten möglicherweise veraltet",
      today: "heute",
      precip: (p: number) => `${p}% Regen`,
      weekdayShort: (d: Date) =>
        new Intl.DateTimeFormat("de-DE", { weekday: "short", timeZone: "Europe/Berlin" }).format(d),
      hourLabel: (d: Date) =>
        new Intl.DateTimeFormat("de-DE", { hour: "2-digit", timeZone: "Europe/Berlin" }).format(d),
      hourlyTitle: "Nächste 12 Stunden",
      radarClose: "Nah",
      radarWide: "50 km",
      radarForecast: "Prognose",
      radarSlider: "Radar-Zeitpunkt",
      radarAttribution: "RainViewer · © OSM/Carto",
    },
    trains: {
      title: "Abfahrten Moosburg",
      south: "Richtung München / Freising",
      north: "Richtung Landshut",
      noDepartures: "Keine Abfahrten in den nächsten Stunden.",
      loading: "Lade Abfahrten…",
      error: "Abfahrten konnten nicht geladen werden.",
      stale: "Daten möglicherweise veraltet",
      cancelled: "Ausfall",
      now: "jetzt",
      inMinutes: (m: number) => (m < 60 ? `in ${m} min` : `in ${Math.floor(m / 60)} h ${m % 60} min`),
      departs: (hhmm: string) => `ab ${hhmm}`,
      arrives: (hhmm: string) => `an ${hhmm}`,
      transferAt: (place: string) => `Umstieg ${place}`,
      transferMinutes: (m: number) => `${m} min`,
      tightTransfer: "knapp",
      missedConnection: "verpasst",
      alternative: (line: string, hhmm: string) => `Stattdessen ${line} ${hhmm}`,
      delayMinutes: (m: number) => `+${m}`,
      platform: (p: string) => `Gl. ${p}`,
      stationInfo: "Zum Bahnhof: zu Fuß 15 min · zügig 10 min · Auto 5 min",
      fixtureMode: (name: string) => `Beispieldaten · ${name}`,
      viewMinimal: "Wichtigste",
      viewFull: "Alle",
      refresh: "Aktualisieren",
      fetchedAgo: (mins: number) =>
        mins < 1 ? "gerade aktualisiert" : mins === 1 ? "vor 1 min aktualisiert" : `vor ${mins} min aktualisiert`,
    },
  },
} as const;
